"""empty message

Revision ID: 095924ecd8c4
Revises: 
Create Date: 2024-02-06 15:55:05.656382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095924ecd8c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lista_de_tarefas', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.create_unique_constraint(None, ['titulo'])

    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', sa.String(length=300), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.drop_column('senha')

    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)

    with op.batch_alter_table('lista_de_tarefas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('descricao',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)

    # ### end Alembic commands ###
