"""empty message

Revision ID: 68147a334633
Revises: e973f9cf91e8
Create Date: 2024-02-07 12:03:28.743737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68147a334633'
down_revision = 'e973f9cf91e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lista_de_tarefas', schema=None) as batch_op:
        batch_op.drop_constraint('lista_de_tarefas_titulo_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lista_de_tarefas', schema=None) as batch_op:
        batch_op.create_unique_constraint('lista_de_tarefas_titulo_key', ['titulo'])

    # ### end Alembic commands ###
